"""
Django settings for oscar_custom project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env()
environ.Env.read_env()
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-)o^iotala&(=bq3abyg&p)blkk5x034p@i$0=a&kj#370j%@ze'
DEBUG = True
ALLOWED_HOSTS = []

# APPS
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    "django.forms",
    'django.contrib.sites',
    'django.contrib.flatpages',

    # oscar
    'oscar_custom.oscar.config.Shop',
    'oscar_custom.oscar.apps.analytics.apps.AnalyticsConfig',
    'oscar_custom.oscar.apps.checkout.apps.CheckoutConfig',
    'oscar_custom.oscar.apps.address.apps.AddressConfig',
    'oscar_custom.oscar.apps.shipping.apps.ShippingConfig',
    'oscar_custom.oscar.apps.catalogue.apps.CatalogueConfig',
    'oscar_custom.oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    'oscar_custom.oscar.apps.communication.apps.CommunicationConfig',
    'oscar_custom.oscar.apps.partner.apps.PartnerConfig',
    'oscar_custom.oscar.apps.basket.apps.BasketConfig',
    'oscar_custom.oscar.apps.payment.apps.PaymentConfig',
    'oscar_custom.oscar.apps.offer.apps.OfferConfig',
    'oscar_custom.oscar.apps.order.apps.OrderConfig',
    'oscar_custom.oscar.apps.customer.apps.CustomerConfig',
    'oscar_custom.oscar.apps.search.apps.SearchConfig',
    'oscar_custom.oscar.apps.voucher.apps.VoucherConfig',
    'oscar_custom.oscar.apps.wishlists.apps.WishlistsConfig',
    'oscar_custom.oscar.apps.dashboard.apps.DashboardConfig',
    'oscar_custom.oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.users.apps.UsersDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
    'oscar_custom.oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',

    # 3rd-party apps that oscar depends on
    'widget_tweaks',
    'haystack',
    'treebeard',
    'sorl.thumbnail',
    'django_tables2',

    # 3rd-party apps
    'django_htmx',

    # local apps
]

# MIDDLEWARE
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oscar_custom.oscar.apps.basket.middleware.BasketMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
]

# URLS
# ------------------------------------------------------------------------------
ROOT_URLCONF = 'oscar_custom.urls'
WSGI_APPLICATION = 'oscar_custom.wsgi.application'

# TEMPLATES
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                'django.contrib.messages.context_processors.messages',
                'oscar_custom.oscar.apps.search.context_processors.search_form',
                'oscar_custom.oscar.apps.checkout.context_processors.checkout',
                'oscar_custom.oscar.apps.communication.notifications.context_processors.notifications',
                'oscar_custom.oscar.core.context_processors.metadata',
            ],
        },
    },
]
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# DATABASE
# ------------------------------------------------------------------------------
DATABASES = {"default": env.db("DATABASE_URL")}
DATABASES["default"]["ATOMIC_REQUESTS"] = True

# PASSWORDS
# ------------------------------------------------------------------------------
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
]

# SECURITY
# ------------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"

# GENERAL
# ------------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}

# OSCAR
# ------------------------------------------------------------------------------
from .oscar.defaults import *
SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    'oscar_custom.oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
)
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}

# 3RD PARTY
# ------------------------------------------------------------------------------
# SORL THUMBNAIL
# ------------------------------------------------------------------------------
THUMBNAIL_PREFIX = 'assets/cache/'

# EMAIL
# ------------------------------------------------------------------------------
EMAIL_BACKEND = env("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("DJANGO_EMAIL_HOST")
EMAIL_HOST_USER = env("DJANGO_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("DJANGO_EMAIL_HOST_PASSWORD")
EMAIL_PORT = env.int("DJANGO_EMAIL_PORT")
DEFAULT_FROM_EMAIL = env("DJANGO_DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env("DJANGO_SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = env("DJANGO_EMAIL_SUBJECT_PREFIX", default="")
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 5
